name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports: ['6379:6379']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify installation (Day 0)
        env:
          DATABASE_URL: postgresql://postgres:AD9Zt20BQs5emB7D@db.vrpuqwdaklbkldizcdjl.supabase.co:5432/postgres
        run: |
          echo "✅ Dependencies installed successfully"
